[licenses]
allow = [
    "Apache-2.0",
    "MIT",
]

# The confidence threshold for detecting a license from license text.
# [possible values: any between 0.0 and 1.0].
confidence-threshold = 1.0

[licenses.private]
ignore = true
