name: Rust

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/rust.yml
      - Cargo.*
      - src/**
  pull_request:
    paths:
      - .github/workflows/rust.yml
      - Cargo.*
      - src/**
  workflow_dispatch: { }

env:
  CARGO_TERM_COLOR: always

jobs:
  Rust:
    strategy:
      fail-fast: false
      matrix:
        rust:
          # Ubuntu 24.04
          - 1.75.0

          - '1.76'
          - '1.77'
          - '1.78'
          - '1.79'
          - '1.80'
          - '1.81'
          - '1.82'
          - '1.83'
          - '1.84'

          # Debian 13
          - '1.85'

          - '1.86'
          - '1.87'
          - '1.88'
          - '1.89'
          - '1.90'
          - '1.91'

        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}

      - uses: actions/checkout@v4

      - run: cargo build --verbose
        shell: bash
